// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS7m-c-5MBw7FCezrvvKKm7b9Il70A_i4',
    appId: '1:805457744542:web:6150507179b8c1a56da18f',
    messagingSenderId: '805457744542',
    projectId: 'distribuim-80438',
    authDomain: 'distribuim-80438.firebaseapp.com',
    storageBucket: 'distribuim-80438.firebasestorage.app',
    measurementId: 'G-3YJPP5NQRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADMPjkgAMc5t_UWuwWw4_eLoziBPPrMXM',
    appId: '1:805457744542:android:b8ee239cbadc912f6da18f',
    messagingSenderId: '805457744542',
    projectId: 'distribuim-80438',
    storageBucket: 'distribuim-80438.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2YdJ-Owol5dnaSZzC2xkft6gYYKF8ztM',
    appId: '1:805457744542:ios:7b7fc603d05f407e6da18f',
    messagingSenderId: '805457744542',
    projectId: 'distribuim-80438',
    storageBucket: 'distribuim-80438.firebasestorage.app',
    iosBundleId: 'com.example.appDistribuim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2YdJ-Owol5dnaSZzC2xkft6gYYKF8ztM',
    appId: '1:805457744542:ios:7b7fc603d05f407e6da18f',
    messagingSenderId: '805457744542',
    projectId: 'distribuim-80438',
    storageBucket: 'distribuim-80438.firebasestorage.app',
    iosBundleId: 'com.example.appDistribuim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS7m-c-5MBw7FCezrvvKKm7b9Il70A_i4',
    appId: '1:805457744542:web:6b7ecf4a90a3ff5b6da18f',
    messagingSenderId: '805457744542',
    projectId: 'distribuim-80438',
    authDomain: 'distribuim-80438.firebaseapp.com',
    storageBucket: 'distribuim-80438.firebasestorage.app',
    measurementId: 'G-L06ZC4WXXQ',
  );
}
