// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdXz_LEry0MOREBUv6UbAu562GkZzUhm4',
    appId: '1:295889865344:web:e525868d0d31307590f465',
    messagingSenderId: '295889865344',
    projectId: 'distribuim-a3b61',
    authDomain: 'distribuim-a3b61.firebaseapp.com',
    storageBucket: 'distribuim-a3b61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY5hULjBPeNHYvqAUlVyr5tSgGYk-fSwA',
    appId: '1:295889865344:android:689888a0903c62e990f465',
    messagingSenderId: '295889865344',
    projectId: 'distribuim-a3b61',
    storageBucket: 'distribuim-a3b61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx62vDuOsM0NLqm-d5vkftLtnuGLPeMk8',
    appId: '1:295889865344:ios:d69feb7dd9e6b58490f465',
    messagingSenderId: '295889865344',
    projectId: 'distribuim-a3b61',
    storageBucket: 'distribuim-a3b61.firebasestorage.app',
    iosBundleId: 'com.example.appDistribuim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx62vDuOsM0NLqm-d5vkftLtnuGLPeMk8',
    appId: '1:295889865344:ios:d69feb7dd9e6b58490f465',
    messagingSenderId: '295889865344',
    projectId: 'distribuim-a3b61',
    storageBucket: 'distribuim-a3b61.firebasestorage.app',
    iosBundleId: 'com.example.appDistribuim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdXz_LEry0MOREBUv6UbAu562GkZzUhm4',
    appId: '1:295889865344:web:d5ebccb9264ebbc090f465',
    messagingSenderId: '295889865344',
    projectId: 'distribuim-a3b61',
    authDomain: 'distribuim-a3b61.firebaseapp.com',
    storageBucket: 'distribuim-a3b61.firebasestorage.app',
  );
}
